#! /usr/bin/env bash

# autogenerated by linuxdeploy

# make sure errors in sourced scripts will cause this script to stop
set -e

this_dir="$(readlink -f "$(dirname "$0")")"

if [[ ! -e "/lib/libdatrie.so.1" ]]; then 
	cp -rL "$this_dir/usr/lib/libdatrie.so.1" /lib/
	if [[ ! -e "/usr/lib/libdatrie.so.1" ]]; then 
		cp -rL "$this_dir/usr/lib/libdatrie.so.1" /usr/lib/
	fi 
fi 

#ln -s "$this_dir/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0" "/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0"
#mkdir -p /usr/lib/x86_64-linux-gnu 2>/dev/null
#cp -r "$this_dir/usr/lib/gdk-pixbuf-2.0" "/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0"

source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-gettext.sh"
source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-gtk.sh"
source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-ncurses.sh"

export XDG_DATA_DIRS="$this_dir/usr/share/system-monitoring-center:$this_dir/usr/share:${XDG_DATA_DIRS}"
export XDG_DATA_DIRS="$this_dir/usr/share/system-monitoring-center:$this_dir/usr/share:${XDG_DATA_DIRS:-}"
export PYTHONPATH="$this_dir/usr/share/system-monitoring-center:$this_dir/usr/share/system-monitoring-center/systemmonitoringcenter:$this_dir/usr/lib/python/site-packages:{$PYTHONPATH:-}"
export NO_AT_BRIDGE=1
export DISPLAY=:0.0

export DRI_PRIME=1
export AMD_VULKAN_ICD=RADV
export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
export NO_AT_BRIDGE=1
export XDG_MENU_PREFIX=batocera-
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_CURRENT_DESKTOP=XFCE
export DESKTOP_SESSION=XFCE
export QT_FONT_DPI=112
export QT_SCALE_FACTOR=1
export GDK_SCALE=1
export LD_LIBRARY_PATH="/userdata/system/switch/extra/yuzu:${LD_LIBRARY_PATH}"
export GDK_SCALE=1
export QT_PLUGIN_PATH="$this_dir/usr/lib/qt6/plugins:$this_dir/usr/lib/qt5/plugins:$this_dir/usr/lib/qt/plugins:$this_dir/usr/lib/qt/qt5plugins:/usr/lib/qt/plugins:${QT_PLUGIN_PATH}"
export QT_QPA_PLATFORM_PLUGIN_PATH="${QT_PLUGIN_PATH}"
export XDG_CONFIG_HOME=/userdata/system/configs
export XDG_CACHE_HOME=/userdata/system/.cache
export QT_QPA_PLATFORM=xcb
export LD_LIBRARY_PATH="$this_dir/usr/lib:$this_dir/usr/lib/qt5:$this_dir/usr/lib/qt6:${LD_LIBRARY_PATH}"
export PATH="$this_dir/usr/bin:$this_dir/usr/lib/qt5/bin:$this_dir/usr/lib/qt5/libexec:${PATH}"

mkdir -p /usr/share 2>/dev/null
ln -sf $this_dir/usr/share/cockatrice /usr/share/cockatrice
ln -sf $this_dir/usr/bin/cockatrice /usr/bin/cockatrice
ln -sf $this_dir/usr/bin/oracle /usr/bin/oracle

chown -R batocera:batocera /usr/bin/cockatrice
chown -R batocera:batocera /usr/bin/oracle
chown -R batocera:batocera /usr/share/cockatrice

#exec "$this_dir/usr/bin/cockatrice" "$@"
#PATH="$this_dir/usr/bin:$this_dir/usr/lib/qt5/bin:$this_dir/usr/lib/qt5/libexec:${PATH}" 

exec /usr/bin/cockatrice "${@}"
